### PR TITLE
JavaScript - Web jQuery

### PR DESCRIPTION
**Pull request by the1Riddle**
Project 0x15. JavaScript - Web jQuery
Front-end
Co-authored-by: Earl [elv.s.earl@gmail.com](mailto:elv.s.earl@gmail.com)

### CODE REVIEW

**Comment by rezzcode** [comment]
this branch will be merged as soon as the project will be completed.

**Comment by the1Riddle** [comment]
the script in file 5 adds an element to a list when the user clicks on the

**Comment by the1Riddle** [comment]
i will have to merge this first section.

**Comment by rezzcode** [comment]
mmh

**Pull request merged**
